### ISSUE TITLE
ERROR 0x4E7 - Transport level error while connecting to http://localhost:13291: general error 0x4E7

### ISSUE THREAD

**Issue by rcaldas88** [zbx-sadman/KSC#2]
Hi, Sadman.

I am logged into my KSC Server and cant perform the basic tests with your script. Check below the test performed:

```
PS C:\zabbix\scripts> .\ksc.ps1 -Verbose -ServerAddress localhost:13291
MODO DETALHADO: 06/14/2018 11:15:57 Connecting to Kaspersky Security Center on localhost:13291
AVISO: Connection Error (Exceção ao chamar "Connect" com "1" argumento(s): "Transport level error while connecting to
http://localhost:13291: general error 0x4E7")
```

In the script file, I've added the information below:

```
Line 143 - Set-Variable -Option Constant -Name "DefaultAdmServerLocation" -Value "localhost:13291"
Line 352-353-354 - KSC access information.
```

Do I need any more information to connect the script?

**Comment by zbx-sadman** [comment]
Hello

Are you really use KSC 10 **SP2**?

...and you don't need to change script variables, just use _-Username / -Userpass  / -UserDomain_ options to .ps1 calling,

**Comment by imanihb2007** [comment]
> Hello
> 
> Are you really use KSC 10 **SP2**?
> 
> ...and you don't need to change script variables, just use _-Username / -Userpass / -UserDomain_ options to .ps1 calling,

how i can change username / usepass ? can say one exaple

**Comment by zbx-sadman** [comment]
ksc.ps1 ... -Username _NAME_ -Userpass _PASS_ -UserDomain _DOMAIN_
